### PR TITLE
Fix: #139

### PR DESCRIPTION
**Pull request by Archisman-Mridha**

### CODE REVIEW

**Comment by gagbo** [comment]
Hello,

Thanks for the contribution. It looks probably fine (I only had a cursory look right now), but it’s lacking a test case to make sure that the label is applied properly. The best way to test this is probably to have a look at what’s being done in other tests, where we produce calls and check the output of metrics for expected lines like [here](https://github.com/autometrics-dev/autometrics-rs/blob/main/autometrics/tests/integration_test.rs)

**Comment by Archisman-Mridha** [comment]
@gagbo I have written a test as you requested. Please let me know if any further changes are required.

**Comment by gagbo** [comment]
Sorry for the delay, it’s been a bit hectic the last few days!! I’ll review everything tomorrow!

**Review by gagbo — APPROVED** [review]
Thanks for the contribution, it looks nice!

**Pull request merged**
